version: '3.8'
services:
  diary-mysql:
    image: mysql:8.0
    container_name: diary-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # 루트 비밀번호
      MYSQL_DATABASE: diarydb # 만들고 싶은 DB 이름
      MYSQL_USER: diaryuser # 사용자 이름
      MYSQL_PASSWORD: diarypass # 사용자 비밀번호
    ports:
      - ' :3306' # 외부 포트:컨테이너 내부 포트
    volumes:
      - diary-db-data:/var/lib/mysql # 볼륨으로 데이터 유지

volumes:
  diary-db-data:
